'use strict';
const $ = id => document.getElementById(id);
let current=procedures[0],progress=0,playing=false,lastTime=0,category='All',section='lab',lastStep=-1;
const clamp=(n)=>Math.max(0,Math.min(1,n));
const phase=(start,end)=>clamp((progress-start)/(end-start));
const sourceURL=p=>p.source.startsWith('https://')?p.source:p.source==='biopsies'?'https://www.radiologyinfo.org/en/info/biopgen':`https://www.radiologyinfo.org/en/info/${p.source}`;
function draw(){RadiologyViewer.set(current,progress,playing);$('diagram').setAttribute('aria-label',`Synthetic imaging simulation of ${current.name}: ${current.steps[Math.min(4,Math.floor(progress*5))][0]}. Not a patient image.`)}
function renderLibrary(){const query=$('search').value.toLowerCase();let filtered=procedures.filter(p=>(category==='All'||p.category===category)&&`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(query));$('procedureList').innerHTML=filtered.map(p=>`<button class="procedure-item ${p.id===current.id?'selected':''}" data-id="${p.id}" aria-pressed="${p.id===current.id}"><span class="item-icon" aria-hidden="true">${p.icon}</span><span><b>${p.name}</b><small>${p.category} · 5 stages</small></span></button>`).join('')||'<p class="muted">No procedures found. Try another search or category.</p>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>selectProcedure(b.dataset.id))}
function stop(){playing=false;$('play').textContent=progress>=1?'↺ Replay sequence':'▶ Play sequence'}
function update(){if(!playing)$('play').textContent=progress>=1?'↺ Replay sequence':'▶ Play sequence';const step=Math.min(4,Math.floor(progress*5));$('timeline').value=Math.round(progress*1000);$('percentage').textContent=`${Math.round(progress*100)}%`;$('stepCounter').textContent=`STAGE ${step+1} OF 5`;if(step!==lastStep){$('stepTitle').textContent=current.steps[step][0];$('stepText').textContent=current.steps[step][1];$('sceneCaption').textContent=current.steps[step][0];$('lessonNumber').textContent=`0${step+1}`;document.querySelectorAll('[data-step]').forEach((b,i)=>{b.classList.toggle('active',i===step);b.setAttribute('aria-current',i===step?'step':'false')});lastStep=step}draw()}
function selectProcedure(id){current=procedures.find(p=>p.id===id)||procedures[0];progress=0;lastStep=-1;stop();$('category').textContent=`${current.category.toUpperCase()} / PROCEDURE ${String(procedures.indexOf(current)+1).padStart(2,'0')}`;$('procedureTitle').textContent=current.name;$('description').textContent=current.description;$('modality').textContent=current.modality;const ct=['drain','biopsy','ablation'].includes(current.type),us=['thoracentesis','paracentesis'].includes(current.type);$('viewLabel').textContent=ct?'CT / AXIAL DEMONSTRATION':us?'ULTRASOUND / SYNTHETIC':current.view;document.querySelector('[data-view="fluoro"]').textContent=ct?'CT slice':us?'B-mode':'Fluoro';document.querySelector('[data-view="dsa"]').disabled=ct||us;$('contrastRun').disabled=ct||us||['access','port'].includes(current.type);RadiologyViewer.configure('mode','fluoro');document.querySelectorAll('[data-view]').forEach(b=>{const selected=b.dataset.view==='fluoro';b.classList.toggle('active',selected);b.setAttribute('aria-pressed',selected)});$('objective').textContent=current.objective;$('tools').innerHTML=suiteConfiguration(current).kit.map(k=>equipmentCatalog[k].name).map(t=>`<div class="tool"><span aria-hidden="true">◇</span>${t}</div>`).join('');$('caution').textContent=current.caution;$('question').textContent=current.question;$('feedback').textContent='';$('answers').innerHTML=current.answers.map((a,i)=>`<button data-answer="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const right=Number(b.dataset.answer)===current.correct;b.classList.add(right?'correct':'wrong');$('feedback').textContent=right?`Correct. ${current.explanation}`:'Not quite. Try another answer.'});$('source').href=sourceURL(current);$('steps').innerHTML=current.steps.map((s,i)=>`<button data-step="${i}">0${i+1} ${s[0]}</button>`).join('');document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{stop();progress=Number(b.dataset.step)/5+.001;update()});renderLibrary();update();history.replaceState(null,'',`#${current.id}`);window.dispatchEvent(new CustomEvent('ir:procedure',{detail:current}))}
function tick(time){RadiologyViewer.set(current,progress,playing);if(playing){const delta=lastTime?Math.min(time-lastTime,100):0;progress=Math.min(1,progress+delta/25000*Number($('speed').value));update();if(progress>=1)stop()}lastTime=time;requestAnimationFrame(tick)}
$('play').onclick=()=>{if(playing)stop();else{if(progress>=1)progress=0;playing=true;$('play').textContent='Ⅱ Pause sequence';lastTime=0}};
$('reset').onclick=()=>{progress=0;stop();update()};$('timeline').oninput=e=>{stop();progress=Number(e.target.value)/1000;update()};$('search').oninput=renderLibrary;
$('filters').innerHTML=['All','Vascular','Access','Drainage','Oncology'].map(c=>`<button data-category="${c}" class="${c==='All'?'active':''}" aria-pressed="${c==='All'}">${c}</button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderLibrary()});$('count').textContent=procedures.length;
function showSection(name){stop();section=name;['welcome','lab','suite','references'].forEach(id=>$(id).hidden=id!==name);['welcomeNav','proceduresNav','suiteNav','referencesNav'].forEach((id,i)=>$(id).classList.toggle('active',['welcome','lab','suite','references'][i]===name));window.dispatchEvent(new CustomEvent('ir:section',{detail:name}))}
$('proceduresNav').onclick=()=>showSection('lab');$('suiteNav').onclick=()=>showSection('suite');$('referencesNav').onclick=()=>showSection('references');document.querySelector('.brand').onclick=e=>{e.preventDefault();showSection('welcome')};
$('referenceLinks').innerHTML=[...new Map(procedures.map(p=>[p.source,p])).values()].map(p=>`<a href="${sourceURL(p)}" target="_blank" rel="noopener">${p.name} · Clinical overview ↗</a>`).join('');
const media=matchMedia('(prefers-reduced-motion: reduce)');$('reduceMotion').checked=media.matches;document.body.classList.toggle('no-motion',media.matches);$('reduceMotion').onchange=e=>{document.body.classList.toggle('no-motion',e.target.checked);RadiologyViewer.configure('grain',!e.target.checked)};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});RadiologyViewer.configure('mode',b.dataset.view)});
$('windowLevel').oninput=e=>RadiologyViewer.configure('window',Number(e.target.value));
$('zoomImage').onchange=e=>RadiologyViewer.configure('zoom',Number(e.target.value));
$('contrastRun').onclick=()=>RadiologyViewer.inject();
$('annotations').onchange=e=>RadiologyViewer.configure('labels',e.target.checked);
RadiologyViewer.configure('grain',!media.matches);
window.IRLab={getCurrent:()=>current,getProgress:()=>progress,isPlaying:()=>playing,select:selectProcedure,show:showSection,seek(value){stop();progress=Math.max(0,Math.min(1,value));update()},togglePlay(){ $('play').click() },reset(){ $('reset').click() }};
const initialCase=procedures.some(p=>p.id===location.hash.slice(1))?location.hash.slice(1):null;selectProcedure(initialCase);showSection(initialCase?'suite':'welcome');requestAnimationFrame(tick);

const rooms=[{id:'vascular',name:'Angiography suite',subtitle:'Vascular & embolization',image:'abdomen',ids:procedures.filter(p=>p.category==='Vascular').map(p=>p.id)},{id:'oncology',name:'Interventional oncology',subtitle:'Y-90 · TACE · biopsy · ablation',image:'ct',ids:procedures.filter(p=>p.category==='Oncology').map(p=>p.id)},{id:'access',name:'Access & drainage',subtitle:'Venous access · image-guided drains',image:'chest',ids:procedures.filter(p=>['Access','Drainage'].includes(p.category)).map(p=>p.id)}];
$('roomChoices').innerHTML=rooms.map((r,i)=>`<article class="room-choice"><div class="room-image"><img src="assets/${r.image}.png" alt="Synthetic ${r.subtitle} teaching image"><span>SUITE 0${i+1}</span></div><div class="room-choice-body"><small>${r.subtitle}</small><h2>${r.name}</h2><label for="room-${r.id}">Choose your procedure</label><select id="room-${r.id}">${r.ids.map(id=>{const p=procedures.find(p=>p.id===id);return `<option value="${id}">${p.name}</option>`}).join('')}</select><button class="enter-room" data-room="${r.id}">Enter suite <span>↗</span></button></div></article>`).join('');
document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{selectProcedure($('room-'+b.dataset.room).value);showSection('suite')});
$('welcomeNav').onclick=()=>showSection('welcome');

$('referenceLinks').insertAdjacentHTML('beforeend','<a href="https://www.medtronic.com/en-gb/healthcare-professionals/products/cardiovascular/peripheral-embolization/onyx-liquid-embolic-system.html" target="_blank" rel="noopener">EVOH liquid embolic · Manufacturer overview ↗</a><a href="https://www.accessdata.fda.gov/cdrh_docs/pdf/P990040S034D.pdf" target="_blank" rel="noopener">n-BCA system · Product-specific labeling ↗</a>');

$('referenceLinks').insertAdjacentHTML('beforeend','<a href="https://pubmed.ncbi.nlm.nih.gov/25962991/" target="_blank" rel="noopener">Pelvic artery anatomy · Angiographic classification study ↗</a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC13282349/" target="_blank" rel="noopener">GAE blush and embolic endpoints · Study ↗</a><a href="https://usa.guerbet.com/en-us/products-solutions/contrast-media/lipiodolr-ethiodized-oil-injection" target="_blank" rel="noopener">Iodized oil · Manufacturer information ↗</a>');
