(() => {
const el=id=>document.getElementById(id),nav=window.IRNavigation;
const workstation=document.querySelector('.suite-workstation');workstation.insertBefore(el('navigationPanel'),document.querySelector('.monitor-column'));
const exposure={pedal:false,latched:false,shielded:false,shieldReadyAt:0,dsaUntil:0,role:'resident'};
const active=()=>exposure.pedal||exposure.latched||performance.now()<exposure.dsaUntil;
const canManipulate=()=>active()&&!exposure.shielded&&performance.now()>=exposure.shieldReadyAt;
const mode=()=>performance.now()<exposure.dsaUntil?'dsa':'fluoro';
function setPedal(on){if(exposure.dsaUntil>performance.now())return;exposure.pedal=on;el('fluoroPedal').classList.toggle('active',on)}
function setRole(role){exposure.role=role;el('operatorRole').value=role;el('roleTask').textContent=role==='nurse'?'Nurse · Prepare the tray, assist delivery and monitor the team.':role==='attending'?'Attending · Supervise navigation and review the selected territory.':'Resident · Navigate the wire, position the catheter and assess contrast.';document.body.dataset.irRole=role;window.dispatchEvent(new CustomEvent('ir:role',{detail:role}));}
function shield(){if(performance.now()<exposure.dsaUntil)return;exposure.shielded=!exposure.shielded;exposure.shieldReadyAt=performance.now()+4800;stopExposure();nav.hold(0);if(nav.get().delivering)nav.stop();el('shieldTeam').setAttribute('aria-pressed',exposure.shielded);el('shieldTeam').textContent=exposure.shielded?'Return team to table':'Move team to control room';el('dsaRun').disabled=!exposure.shielded;el('clinicalRoom').classList.toggle('team-shielded',exposure.shielded);window.dispatchEvent(new CustomEvent('ir:shield',{detail:exposure.shielded}));}
function stopExposure(){exposure.pedal=false;exposure.latched=false;exposure.dsaUntil=0;el('fluoroLatch').setAttribute('aria-pressed','false');setPedal(false)}
el('operatorRole').onchange=e=>setRole(e.target.value);
el('fluoroPedal').onpointerdown=e=>{e.preventDefault();el('fluoroPedal').setPointerCapture(e.pointerId);setPedal(true)};
el('fluoroPedal').onpointerup=()=>setPedal(false);el('fluoroPedal').onpointercancel=()=>setPedal(false);
el('fluoroPedal').onkeydown=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();setPedal(true)}};el('fluoroPedal').onkeyup=()=>setPedal(false);
el('navExposure').onclick=()=>el('fluoroLatch').click();
el('fluoroLatch').onclick=()=>{exposure.latched=!exposure.latched;el('fluoroLatch').setAttribute('aria-pressed',String(exposure.latched))};
el('shieldTeam').onclick=shield;
el('dsaRun').onclick=()=>{if(!exposure.shielded||performance.now()<exposure.shieldReadyAt)return;exposure.latched=false;exposure.pedal=false;exposure.dsaUntil=performance.now()+8000;el('fluoroLatch').setAttribute('aria-pressed','false');window.RadiologyViewer?.inject();if(['gae','pae'].includes(window.IRLab.getCurrent().id))nav.inject();};
el('showBlood').onchange=e=>{document.querySelector('.clinical-blood').hidden=!e.target.checked;window.dispatchEvent(new CustomEvent('ir:blood',{detail:e.target.checked}))};
function bindMove(id,direction){const b=el(id);let held=false;b.onpointerdown=e=>{e.preventDefault();held=true;b.setPointerCapture(e.pointerId);if(!canManipulate()){el('navExposureStatus').textContent='Image held — turn fluoroscopy on to see wire movement.';return;}nav.move(direction*.07);nav.hold(direction)};b.onpointerup=()=>{held=false;nav.hold(0)};b.onpointercancel=()=>{held=false;nav.hold(0)};b.onclick=e=>{if(e.detail===0&&!held){if(canManipulate())nav.move(direction*.12);else el('navExposureStatus').textContent='Image held — turn fluoroscopy on to see wire movement.';}};}
bindMove('wireForward',1);bindMove('wireBack',-1);
el('pelvicVariant').onchange=e=>{const tool=nav.get().tool;nav.reset(nav.get().access,'pae',e.target.value);nav.setTool(tool)};
el('wireTorque').oninput=e=>{nav.setTorque(e.target.value);window.dispatchEvent(new CustomEvent('ir:torque',{detail:Number(e.target.value)}))};
el('navInstrument').onchange=e=>window.dispatchEvent(new CustomEvent('ir:select-tool',{detail:e.target.value}));el('navContrast').onclick=()=>el('suiteContrast').click();
el('seatCatheter').onclick=()=>{if(canManipulate())nav.seat();else el('navigationStatus').textContent='Turn fluoroscopy on to observe microcatheter tracking.'};el('embolizeStart').onclick=()=>nav.start();el('embolizeStop').onclick=()=>nav.stop();
el('followWire').onchange=e=>nav.setFollow(e.target.checked);el('roadmapOverlay').onchange=e=>nav.setRoadmap(e.target.checked);
let branchKey='',workUntil=0,previousPosition=0,previousCatheterPosition=0;window.addEventListener('ir:navigation',()=>{if(nav.get().position!==previousPosition||nav.get().catheterPosition!==previousCatheterPosition){workUntil=performance.now()+800;previousPosition=nav.get().position;previousCatheterPosition=nav.get().catheterPosition;}});
function updateNavigation(){const s=nav.get(),n=nav.current(),view=nav.display(),catheter=['microcatheter','liquidMicro'].includes(s.tool);el('wireForward').textContent=catheter?'Advance microcatheter →':'Advance wire →';el('wireBack').textContent=catheter?'← Retract microcatheter':'← Retract wire';el('vesselName').textContent=view.node.name;el('navigationRoute').textContent=view.path.map(k=>nav.nodes[k].name.split(' · ')[0]).join(' → ');el('navigationStatus').textContent=s.message;el('vesselProgress').textContent=`${view.device==='catheter'?'Microcatheter':'Wire'}: ${Math.round(view.position*100)}% · ${Object.values(s.treated).filter(v=>v>=1).length} territories treated`;el('wireTorque').value=s.torque;el('torqueValue').textContent=s.torque+'°';el('embolizeStop').disabled=!s.delivering;const key=nav.id()+':'+(s.position>=.99)+':'+catheter;if(key!==branchKey){branchKey=key;el('branchChoices').innerHTML=n.children.map(k=>`<button data-vessel="${k}" ${s.position<.99||catheter?'disabled':''}>${nav.nodes[k].name}<small>Tip direction: ${nav.nodes[k].angle}°</small></button>`).join('')||'<span class="muted">End of this modeled branch. Retract to the previous junction.</span>';el('branchChoices').querySelectorAll('[data-vessel]').forEach(b=>b.onclick=()=>nav.enter(b.dataset.vessel))}}
window.addEventListener('ir:navigation',updateNavigation);
window.addEventListener('ir:procedure',e=>{stopExposure();nav.reset('Femoral',e.detail.id);el('navigationPanel').hidden=!['gae','pae'].includes(e.detail.id);workstation.classList.toggle('manual-case',['gae','pae'].includes(e.detail.id));el('navigationTitle').textContent=e.detail.id.toUpperCase()+' · MANUAL VESSEL NAVIGATION';el('pelvicVariantLabel').hidden=e.detail.id!=='pae';el('pelvicVariant').value='direct';el('showBlood').checked=false;document.querySelector('.clinical-blood').hidden=true;updateNavigation()});
el('suiteReset').addEventListener('click',()=>{stopExposure();const s=nav.get();nav.reset(s.access,window.IRLab.getCurrent().id,s.variant);if(exposure.shielded)shield();});
window.addEventListener('ir:section',e=>{if(e.detail!=='suite'){stopExposure();nav.hold(0);if(nav.get().delivering)nav.stop()}});
window.addEventListener('blur',()=>{setPedal(false);nav.hold(0)});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopExposure();nav.hold(0);if(nav.get().delivering)nav.stop()}});
const handsCanvas=el('handsCanvas');
function hands(t){const s=nav.get(),tool=s.tool,name=equipmentCatalog[tool]?.name||'Equipment';if(window.IRInHand){window.IRInHand.mount(handsCanvas);window.IRInHand.setTool(tool);window.IRInHand.setState({holding:s.holding,torque:s.torque,delivering:s.delivering,contrast:performance.now()<s.contrastUntil,shielded:exposure.shielded,role:exposure.role,position:s.position,catheterPosition:s.catheterPosition});}el('handCaption').textContent=exposure.shielded?'CONTROL ROOM · OBSERVING THROUGH LEAD GLASS':`${exposure.role.toUpperCase()} · ${name}${s.delivering?' · delivering':s.holding>0?' · advancing':s.holding<0?' · retracting':''}`;}
window.addEventListener('ir:tool-selected',()=>{workUntil=performance.now()+1200});
function safelyWorking(){const s=nav.get();return !exposure.shielded&&(s.holding||s.delivering||performance.now()<workUntil||performance.now()<s.contrastUntil)}
let last=0;function frame(ms){requestAnimationFrame(frame);if(ms-last<40||document.hidden)return;last=ms;if(!canManipulate())nav.hold(0);const away=exposure.shielded||ms<exposure.shieldReadyAt;for(const id of ['wireForward','wireBack','wireTorque','seatCatheter','embolizeStart'])el(id).disabled=away;if(['gae','pae'].includes(window.IRLab?.getCurrent().id))nav.tick(ms);const on=active(),dsa=mode()==='dsa';el('navExposure').textContent=on?'Turn fluoroscopy off':'Turn fluoroscopy on';el('navExposureStatus').textContent=on?'LIVE · wire motion visible on monitor':'IMAGE HELD · turn fluoroscopy on before navigating';document.querySelector('#clinicalRoom').classList.toggle('working',!!safelyWorking());el('exposureLamp').classList.toggle('on',on);el('exposureState').textContent=dsa?`DSA ACQUIRING · ${Math.ceil((exposure.dsaUntil-ms)/1000)} s`:on?'FLUOROSCOPY ON':'EXPOSURE OFF · LAST IMAGE HELD';const xray=window.IRLab?suiteConfiguration(window.IRLab.getCurrent()).modality==='C-arm':true;el('dsaRun').disabled=!xray||!exposure.shielded||ms<exposure.shieldReadyAt||dsa;el('fluoroPedal').disabled=!xray;el('fluoroLatch').disabled=!xray;if(!xray)el('exposureState').textContent='SYNTHETIC '+suiteConfiguration(window.IRLab.getCurrent()).modality.toUpperCase()+' DISPLAY';el('shieldTeam').disabled=dsa||ms<exposure.shieldReadyAt;hands(ms/1000);}
window.IRExposure={active,mode,get:()=>exposure,stop:stopExposure};setRole('resident');requestAnimationFrame(frame);
})();
