(() => {
const sheets={
 access:['micropuncture','wire','sheath','hydrophilic','microwire','syringe','biopsy','tipsNeedle','probe'],
 catheter:['pigtail','cobra','simmons','vertebral','microcatheter','uterine','renal','liquidMicro','aspiration'],
 treatment:['balloon','stent','coils','particles','evoh','nbca','y90','coveredStent','filter'],
 drainage:['drain','biliaryDrain','pleural','ascites','feeding','picc','central','port','ultrasound'],
 ancillary:['needle','oil','chemo']
};
const visuals={};for(const [sheet,ids] of Object.entries(sheets))ids.forEach((id,index)=>visuals[id]={sheet,index,rows:sheet==='ancillary'?1:3});
function photo(id,className=''){const v=visuals[id];if(!v)return '';return `<span class="device-photo ${className}" aria-hidden="true" style="--device-image:url('assets/equipment/${v.sheet}-sheet.png');--device-x:${v.index%3*50}%;--device-y:${v.rows===1?0:Math.floor(v.index/3)*50}%;--device-rows:${v.rows}"></span>`;}
function card(id,selected){const t=equipmentCatalog[id];return `<button class="device-card${selected?' active':''}" data-tool="${id}" aria-pressed="${selected}" aria-label="${t.name}">${photo(id)}<span class="device-copy"><small>${t.group}</small><b>${t.name}</b><span class="device-selection">${selected?'Selected · in hand':'Select device'}</span></span></button>`;}
let inspectedId=null;
function inspect(id){const t=equipmentCatalog[id];if(!t)return;const changed=inspectedId!==id;inspectedId=id;const host=document.getElementById('equipmentInspector');host.innerHTML=`<button class="device-inspect-image" aria-label="Enlarge ${t.name}">${photo(id)}</button><div class="device-inspect-copy"><span class="eyebrow">SELECTED EQUIPMENT · ${t.group.toUpperCase()}</span><h3>${t.name}</h3><p>${t.description}</p><div class="device-inspect-actions"><button class="device-motion-button">Explore device in 3D</button><button class="device-photo-button">View photograph ↗</button></div></div>`;host.querySelector('.device-inspect-image').onclick=()=>open(id,'photo');host.querySelector('.device-motion-button').onclick=()=>open(id,'motion');host.querySelector('.device-photo-button').onclick=()=>open(id,'photo');if(changed&&!reduced())host.animate([{opacity:.55,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:250,easing:'ease-out'});}
function open(id,view='photo'){const t=equipmentCatalog[id],dialog=document.getElementById('deviceDialog');window.IRDeviceBench?.dispose();dialog.innerHTML=`<div class="device-dialog-header"><span>DEVICE DETAIL · ${t.name.toUpperCase()}</span><button aria-label="Close equipment detail">Close ×</button></div><div class="device-view-tabs" role="group" aria-label="Equipment view"><button data-device-view="photo">Photograph</button><button data-device-view="motion">Interactive 3D</button></div>${photo(id,'detail-photograph')}<div id="deviceBenchHost" hidden></div><div class="device-dialog-copy"><span class="eyebrow">${t.group.toUpperCase()}</span><h2>${t.name}</h2><p>${t.description}</p><small>Generated equipment illustration. Geometry and scale are illustrative.</small></div>`;dialog.querySelector('.device-dialog-header button').onclick=()=>dialog.close();dialog.onclose=()=>window.IRDeviceBench?.dispose();function change(mode){const host=dialog.querySelector('#deviceBenchHost');dialog.querySelector('.detail-photograph').hidden=mode!=='photo';host.hidden=mode!=='motion';dialog.querySelectorAll('[data-device-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.deviceView===mode));window.IRDeviceBench?.dispose();if(mode==='motion'){if(window.IRDeviceBench)window.IRDeviceBench.mount(host,id);else host.innerHTML='<p class="bench-unavailable">The 3D viewer is loading. Select Photograph, then try Interactive 3D again.</p>';}}dialog.querySelectorAll('[data-device-view]').forEach(b=>b.onclick=()=>change(b.dataset.deviceView));dialog.showModal();change(view);}
function reduced(){return matchMedia('(prefers-reduced-motion: reduce)').matches||document.getElementById('reduceMotion')?.checked;}
function transfer(id){if(reduced())return;const source=document.querySelector(`.floating-tray [data-tool="${id}"] .device-photo`),target=document.querySelector('#equipmentInspector .device-photo');if(!source||!target)return;const a=source.getBoundingClientRect(),b=target.getBoundingClientRect();if(a.top<0||a.bottom>innerHeight||b.top<0||b.top>innerHeight)return;const ghost=document.createElement('div');ghost.className='equipment-transfer';ghost.innerHTML=photo(id);Object.assign(ghost.style,{left:a.left+'px',top:a.top+'px',width:a.width+'px',height:a.height+'px'});document.body.append(ghost);const animation=ghost.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${b.left-a.left}px,${b.top-a.top}px) scale(${b.width/a.width})`,opacity:.15}],{duration:420,easing:'cubic-bezier(.2,.65,.3,1)',fill:'forwards'});animation.onfinish=()=>ghost.remove();}
const imageCache={};function draw(ctx,id,x,y,size){const v=visuals[id];if(!v)return;let im=imageCache[v.sheet];if(!im){im=new Image();im.src=`assets/equipment/${v.sheet}-sheet.png`;imageCache[v.sheet]=im;}if(!im.complete||!im.naturalWidth)return;const w=im.naturalWidth/3,h=im.naturalHeight/v.rows;ctx.drawImage(im,v.index%3*w,Math.floor(v.index/3)*h,w,h,x,y,size,size);}
window.IREquipment={visuals,photo,card,inspect,draw,transfer};
})();
