(() => {
const $=id=>document.getElementById(id),workstation=document.querySelector('.suite-workstation'),small=matchMedia('(max-width:780px), (max-width:950px) and (max-height:500px)');
const panel=document.createElement('section');panel.className='phone-workstation';panel.setAttribute('aria-label','Touch imaging workstation');
panel.innerHTML=`<div class="phone-tabs" aria-label="Phone view">${[['room','Room'],['live','Live'],['dsa','DSA'],['vitals','Vitals'],['hands','Hands']].map(([id,label])=>`<button data-phone-view="${id}" aria-pressed="${id==='live'}">${label}</button>`).join('')}</div><div class="phone-screen"><canvas width="640" height="640" aria-label="Enlarged selected simulation monitor"></canvas><div class="phone-zoom"><button data-zoom="out" aria-label="Zoom image out">−</button><button data-zoom="reset" aria-label="Reset image zoom">1×</button><button data-zoom="in" aria-label="Zoom image in">+</button></div></div><div class="phone-status"></div><div class="phone-actions"><button data-phone-action="exposure" aria-pressed="false">Fluoro off</button><button data-phone-action="contrast">Contrast</button><button data-phone-action="equipment">Equipment ↓</button></div>`;
workstation.prepend(panel);
const canvas=panel.querySelector('canvas'),ctx=canvas.getContext('2d'),status=panel.querySelector('.phone-status'),zoomControls=panel.querySelector('.phone-zoom');let view='live',zoom=1,pan={x:0,y:0},last=0,drag=null;
function sync(){canvas.style.touchAction=zoom>1?'none':'pan-y';workstation.classList.toggle('phone-imaging-active',small.matches&&view!=='room');workstation.classList.toggle('phone-room-active',small.matches&&view==='room');panel.querySelectorAll('[data-phone-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.phoneView===view));zoomControls.hidden=!['live','dsa'].includes(view);canvas.setAttribute('aria-label',({live:'Enlarged live synthetic image',dsa:'Saved DSA or unsubtracted run',vitals:'Enlarged simulated patient vital signs',hands:'Selected instrument in gloved hands'})[view]||'Room view');}
panel.querySelectorAll('[data-phone-view]').forEach(b=>b.onclick=()=>{view=b.dataset.phoneView;zoom=1;pan={x:0,y:0};panel.querySelector('[data-zoom=reset]').textContent='1×';sync();});small.addEventListener('change',()=>{drag=null;sync();});
panel.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>{zoom=b.dataset.zoom==='reset'?1:Math.min(3,Math.max(1,zoom+(b.dataset.zoom==='in'?.5:-.5)));if(zoom===1)pan={x:0,y:0};canvas.style.touchAction=zoom>1?'none':'pan-y';panel.querySelector('[data-zoom=reset]').textContent=zoom+'×';});
canvas.onpointerdown=e=>{if(zoom<=1||!['live','dsa'].includes(view))return;canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,pan:{...pan}};};canvas.onpointermove=e=>{if(!drag)return;const r=canvas.getBoundingClientRect(),k=640/Math.min(r.width,r.height),limit=320*(zoom-1);pan.x=Math.max(-limit,Math.min(limit,drag.pan.x+(e.clientX-drag.x)*k));pan.y=Math.max(-limit,Math.min(limit,drag.pan.y+(e.clientY-drag.y)*k));};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
panel.querySelector('[data-phone-action=exposure]').onclick=()=>$('fluoroLatch').click();panel.querySelector('[data-phone-action=contrast]').onclick=()=>$('suiteContrast').click();panel.querySelector('[data-phone-action=equipment]').onclick=()=>document.querySelector('.equipment-panel').scrollIntoView({block:'start',behavior:'auto'});
window.addEventListener('ir:procedure',()=>{zoom=1;pan={x:0,y:0};panel.querySelector('[data-zoom=reset]').textContent='1×';});
function draw(t){requestAnimationFrame(draw);if(!small.matches||document.hidden||$('suite').hidden||t-last<80)return;last=t;const live=window.IRExposure?.active(),xray=$('roomMode').textContent==='C-ARM',button=panel.querySelector('[data-phone-action=exposure]');button.disabled=!xray;button.textContent=xray?(live?'Fluoro on':'Fluoro off'):'Imaging';button.setAttribute('aria-pressed',!!live);panel.querySelector('[data-phone-action=contrast]').disabled=$('suiteContrast').disabled;status.textContent=view==='hands'?$('handCaption').textContent:view==='vitals'?$('vitalsText').textContent:view==='dsa'?$('dsaStatus').textContent:$('exposureState').textContent;if(view==='room')return;const source=view==='hands'?$('handsCanvas'):view==='vitals'?$('vitalsCanvas'):view==='dsa'?window.IRAcquisition?.getFrame():window.RadiologyViewer?.getFrame($('mainImageMode').value);if(!source)return;ctx.fillStyle=view==='hands'?'#244239':'#050a0b';ctx.fillRect(0,0,640,640);const scale=Math.min(640/source.width,640/source.height),w=source.width*scale,h=source.height*scale;ctx.save();ctx.translate(320+pan.x,320+pan.y);ctx.scale(zoom,zoom);ctx.drawImage(source,-w/2,-h/2,w,h);ctx.restore();}
sync();requestAnimationFrame(draw);
})();
