(() => {
const room=document.getElementById('clinicalRoom'),$=id=>document.getElementById(id);
const defaults={imaging:[75,6,23],reference:[50,6,23],vitals:[81,53,18],tray:[3,68,27]};let arranging=false;
function panel(id,label,content){const box=document.createElement('section');box.className='room-equipment';box.dataset.equipment=id;box.innerHTML=`<button class="equipment-handle" aria-label="Move ${label}; use arrow keys">${label} <span>⠿</span></button>`;box.append(content);room.append(box);const handle=box.firstElementChild;function position(x,y){const maxX=100-box.offsetWidth/room.clientWidth*100,maxY=100-box.offsetHeight/room.clientHeight*100;box.style.left=Math.max(0,Math.min(maxX,x))+'%';box.style.top=Math.max(0,Math.min(maxY,y))+'%';}let drag;handle.onpointerdown=e=>{if(!arranging)return;e.preventDefault();handle.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,left:parseFloat(box.style.left),top:parseFloat(box.style.top)}};handle.onpointermove=e=>{if(drag)position(drag.left+(e.clientX-drag.x)/room.clientWidth*100,drag.top+(e.clientY-drag.y)/room.clientHeight*100)};handle.onpointerup=handle.onpointercancel=()=>drag=null;handle.onkeydown=e=>{if(!arranging||!e.key.startsWith('Arrow'))return;e.preventDefault();position(parseFloat(box.style.left)+(e.key==='ArrowRight'?2:e.key==='ArrowLeft'?-2:0),parseFloat(box.style.top)+(e.key==='ArrowDown'?2:e.key==='ArrowUp'?-2:0))};return box;}
panel('imaging','LIVE IMAGING',$('clinicalImaging'));panel('reference','DSA / REFERENCE',$('clinicalReference'));panel('vitals','ANESTHESIA',$('clinicalVitals'));
const tray=document.createElement('div');tray.className='floating-tray';panel('tray','STERILE INSTRUMENT TRAY',tray);
function reset(){room.classList.remove('imaging-focus','equipment-focus','reference-focus');$('focusImaging').textContent='Enlarge imaging';room.querySelectorAll('.room-equipment').forEach(box=>{const [x,y,w]=defaults[box.dataset.equipment];box.style.left=x+'%';box.style.top=y+'%';box.style.width=w+'%'})}
$('focusEquipment').onclick=()=>{room.classList.remove('imaging-focus','reference-focus');$('focusImaging').textContent='Enlarge imaging';room.classList.toggle('equipment-focus')};
$('arrangeRoom').onclick=()=>{arranging=!arranging;room.classList.toggle('arranging',arranging);$('arrangeRoom').setAttribute('aria-pressed',arranging)};
$('resetLayout').onclick=reset;$('focusImaging').onclick=()=>{room.classList.remove('equipment-focus','reference-focus');const on=room.classList.toggle('imaging-focus');$('focusImaging').textContent=on?'Restore room':'Enlarge imaging'};
function moveRoom(){const travel=Number($('tableTravel').value),angle=Number($('gantryRotation').value);const table=room.querySelector('.table-layer'),gantry=room.querySelector('.gantry-layer');if(table)table.style.transform=`translate(${travel*.14}%,${travel*.035}%)`;if(gantry)gantry.style.transform=`rotate(${angle*.22}deg)`;const blood=room.querySelector('.clinical-blood');blood.style.marginLeft=travel*.14+'%';blood.style.marginTop=travel*.00035*room.clientHeight+'px';$('tablePosition').textContent=String(travel);$('gantryAngle').textContent=angle+'°';}
$('tableTravel').addEventListener('input',moveRoom);$('gantryRotation').addEventListener('input',moveRoom);window.addEventListener('ir:procedure',()=>requestAnimationFrame(moveRoom));$('suiteReset').addEventListener('click',()=>requestAnimationFrame(moveRoom));moveRoom();new ResizeObserver(moveRoom).observe(room);
$('clinicalView').addEventListener('click',()=>{room.classList.remove('imaging-focus','equipment-focus','reference-focus');$('focusImaging').textContent='Enlarge imaging';});$('referenceZoom').onclick=()=>{room.classList.remove('imaging-focus','equipment-focus');room.classList.toggle('reference-focus');};
window.addEventListener('ir:kit',e=>{tray.innerHTML=e.detail.kit.map(id=>window.IREquipment.card(id,e.detail.selected===id)).join('');tray.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>window.dispatchEvent(new CustomEvent('ir:select-tool',{detail:b.dataset.tool})));});reset();
})();
