(() => {
const room=document.getElementById('clinicalRoom'),$=id=>document.getElementById(id);
const defaults={imaging:[60,4,30],vitals:[81,43,18],tray:[3,68,27]};let arranging=false;
function panel(id,label,content){const box=document.createElement('section');box.className='room-equipment';box.dataset.equipment=id;box.innerHTML=`<button class="equipment-handle" aria-label="Move ${label}; use arrow keys">${label} <span>⠿</span></button>`;box.append(content);room.append(box);const handle=box.firstElementChild;function position(x,y){const maxX=100-box.offsetWidth/room.clientWidth*100,maxY=100-box.offsetHeight/room.clientHeight*100;box.style.left=Math.max(0,Math.min(maxX,x))+'%';box.style.top=Math.max(0,Math.min(maxY,y))+'%';}let drag;handle.onpointerdown=e=>{if(!arranging)return;e.preventDefault();handle.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,left:parseFloat(box.style.left),top:parseFloat(box.style.top)}};handle.onpointermove=e=>{if(drag)position(drag.left+(e.clientX-drag.x)/room.clientWidth*100,drag.top+(e.clientY-drag.y)/room.clientHeight*100)};handle.onpointerup=handle.onpointercancel=()=>drag=null;handle.onkeydown=e=>{if(!arranging||!e.key.startsWith('Arrow'))return;e.preventDefault();position(parseFloat(box.style.left)+(e.key==='ArrowRight'?2:e.key==='ArrowLeft'?-2:0),parseFloat(box.style.top)+(e.key==='ArrowDown'?2:e.key==='ArrowUp'?-2:0))};return box;}
panel('imaging','LIVE IMAGING',$('clinicalImaging'));panel('vitals','ANESTHESIA',$('clinicalVitals'));
const tray=document.createElement('div');tray.className='floating-tray';panel('tray','STERILE INSTRUMENT TRAY',tray);
function reset(){room.classList.remove('imaging-focus');$('focusImaging').textContent='Enlarge imaging';room.querySelectorAll('.room-equipment').forEach(box=>{const [x,y,w]=defaults[box.dataset.equipment];box.style.left=x+'%';box.style.top=y+'%';box.style.width=w+'%'})}
$('arrangeRoom').onclick=()=>{arranging=!arranging;room.classList.toggle('arranging',arranging);$('arrangeRoom').setAttribute('aria-pressed',arranging)};
$('resetLayout').onclick=reset;$('focusImaging').onclick=()=>{const on=room.classList.toggle('imaging-focus');$('focusImaging').textContent=on?'Restore room':'Enlarge imaging'};
$('clinicalView').addEventListener('click',()=>room.classList.remove('imaging-focus'));
function kit(){tray.replaceChildren();document.querySelectorAll('#equipmentTray button').forEach(original=>{const b=original.cloneNode(true);b.removeAttribute('id');b.onclick=()=>original.click();tray.append(b)})}
new MutationObserver(kit).observe($('equipmentTray'),{childList:true,subtree:true,attributes:true,attributeFilter:['class']});kit();reset();
const staff=[document.querySelector('.clinician-resident'),document.querySelector('.clinician-nurse')];
const positions=[[31,37,26],[6,36,25]], destinations=[[30,27,8],[37,27,8]];let journey=null,shielded=false;
staff.forEach((person,i)=>{const sprite=document.createElement('div');sprite.className='walking-person';sprite.style.backgroundImage=`url(assets/${i?'nurse':'resident'}-walk.png)`;sprite.hidden=true;room.append(sprite);person.walkSprite=sprite;const badge=document.createElement('span');badge.className='lead-badge';badge.textContent='☢ IR';person.badge=badge;room.append(badge)});
window.addEventListener('ir:shield',e=>{shielded=e.detail;journey={start:performance.now(),out:shielded};room.classList.remove('team-shielded')});
function animate(t){requestAnimationFrame(animate);staff.forEach((person,i)=>{let loc=shielded?destinations[i]:positions[i];if(journey){const p=Math.min(1,(t-journey.start)/4800),q=journey.out?p:1-p;const route=[positions[i],i?[49,43,24]:[12,41,24],[18,26,15],destinations[i]],segment=Math.min(2,Math.floor(q*3)),fraction=q*3-segment,a=route[segment],b=route[segment+1];loc=a.map((v,j)=>v+(b[j]-v)*fraction);person.hidden=true;const sp=person.walkSprite;sp.hidden=!$('showTeam').checked;const frame=Math.floor((t-journey.start)/130)%8;sp.style.backgroundPosition=`${(frame%4)*100/3}% ${Math.floor(frame/4)*100}%`;sp.style.left=loc[0]+'%';sp.style.top=loc[1]+'%';sp.style.width=loc[2]+'%';sp.style.height=loc[2]*2.25+'%';sp.style.transform=(journey.out?(b[0]<a[0]):(b[0]>a[0]))?'scaleX(-1)':'none';if(p>=1&&i===1)journey=null;}else{person.walkSprite.hidden=true;person.hidden=!$('showTeam').checked;person.style.cssText=`left:${loc[0]}%;top:${loc[1]}%;width:${loc[2]}%;height:auto;bottom:auto;right:auto;transform:none;transition:none;opacity:${shielded?.7:1}`;const working=room.classList.contains('working');const src=`assets/${working?'working-':''}${i?'nurse':'resident'}.png`;if(person.getAttribute('src')!==src)person.src=src;}person.badge.hidden=shielded||!!journey||!$('showTeam').checked;person.badge.style.left=(loc[0]+loc[2]*.48)+'%';person.badge.style.top=(loc[1]+loc[2]*.7)+'%';});}
requestAnimationFrame(animate);
})();
