import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
const el=id=>document.getElementById(id), host=el('suite3D');
const suite={access:'Femoral (arterial)',tool:'needle',filter:'All',table:0,gantry:0,modality:'C-arm',injectUntil:0,ready:false,lastStage:-1};
const lab=window.IRLab;
const scene=new THREE.Scene();scene.background=new THREE.Color('#829d9c');scene.fog=new THREE.Fog('#829d9c',16,32);
const camera=new THREE.PerspectiveCamera(39,1,.1,60);camera.position.set(7.4,6.5,8.3);
const roomCanvas=document.createElement('canvas');let renderer={isFallback:true,domElement:roomCanvas,setSize(){},render(){}};let rendererAttempted=false;
function enable3D(){if(rendererAttempted)return;rendererAttempted=true;
try{renderer=new THREE.WebGLRenderer({canvas:roomCanvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;host.replaceChildren(renderer.domElement)}catch(error){host.innerHTML='<div class="room-loading">The 3D room needs WebGL. Use the imaging lab in this browser, or open the site in a WebGL-enabled browser.</div>';renderer={isFallback:true,domElement:roomCanvas,setSize(){},render(){}}}
}
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.2,0);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=3.2;controls.maxDistance=15;controls.maxPolarAngle=Math.PI*.47;controls.minPolarAngle=.15;controls.update();
scene.add(new THREE.HemisphereLight('#e8f5ff','#829187',2));const sun=new THREE.DirectionalLight('#fff8e9',3.3);sun.position.set(-3,9,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-7;sun.shadow.camera.right=7;sun.shadow.camera.top=7;sun.shadow.camera.bottom=-7;sun.shadow.normalBias=.025;scene.add(sun);const fill=new THREE.DirectionalLight('#c8ecff',1.3);fill.position.set(6,5,-5);scene.add(fill);
const mats={white:new THREE.MeshStandardMaterial({color:'#d8e6e5',roughness:.3,metalness:.12}),dark:new THREE.MeshStandardMaterial({color:'#25383e',roughness:.38,metalness:.35}),chrome:new THREE.MeshStandardMaterial({color:'#bdcbd0',roughness:.19,metalness:.8}),teal:new THREE.MeshStandardMaterial({color:'#43867f',roughness:.9}),skin:new THREE.MeshStandardMaterial({color:'#cbb2a0',roughness:.64}),joint:new THREE.MeshStandardMaterial({color:'#827e74',roughness:.75}),scrub:new THREE.MeshStandardMaterial({color:'#367da0',roughness:.8}),nurse:new THREE.MeshStandardMaterial({color:'#8564a3',roughness:.85}),anesthesia:new THREE.MeshStandardMaterial({color:'#538573',roughness:.85}),mask:new THREE.MeshStandardMaterial({color:'#b5d8d5',roughness:1}),glove:new THREE.MeshStandardMaterial({color:'#d6deda',roughness:.6}),black:new THREE.MeshStandardMaterial({color:'#132226',roughness:.8}),blue:new THREE.MeshStandardMaterial({color:'#4fa4db',roughness:.45}),amber:new THREE.MeshStandardMaterial({color:'#d3b16d',roughness:.45}),transparent:new THREE.MeshPhysicalMaterial({color:'#dbf4ff',transparent:true,opacity:.35,roughness:.05,metalness:.05})};
function mesh(geometry,material,pos=[0,0,0],parent=scene){const o=new THREE.Mesh(geometry,typeof material==='string'?mats[material]:material);o.position.set(...pos);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function box(w,h,d,pos,mat='white',parent=scene){return mesh(new THREE.BoxGeometry(w,h,d),mat,pos,parent)}
function sphere(rx,ry,rz,pos,mat='skin',parent=scene){const o=mesh(new THREE.SphereGeometry(1,28,20),mat,pos,parent);o.scale.set(rx,ry,rz);return o}
function rod(a,b,r,mat='chrome',parent=scene){const aa=new THREE.Vector3(...a),bb=new THREE.Vector3(...b),delta=bb.clone().sub(aa);const o=mesh(new THREE.CylinderGeometry(r,r,delta.length(),16),mat,aa.clone().add(bb).multiplyScalar(.5).toArray(),parent);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());return o}
function curve(points,r,mat,parent=scene){const path=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));return mesh(new THREE.TubeGeometry(path,48,r,8,false),mat,[0,0,0],parent)}
function textLabel(text,width=2,color='#203f42',bg='#d9e8e7'){const c=document.createElement('canvas');c.width=512;c.height=100;const c2=c.getContext('2d');c2.fillStyle=bg;c2.fillRect(0,0,512,100);c2.fillStyle=color;c2.font='600 31px Arial';c2.textAlign='center';c2.fillText(text,256,62);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const plane=new THREE.Mesh(new THREE.PlaneGeometry(width,width/5.12),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));return plane}
function wheel(x,z,parent=scene){const w=mesh(new THREE.CylinderGeometry(.08,.08,.05,18),'dark',[x,.12,z],parent);w.rotation.z=Math.PI/2}
// Cutaway room and clinical surfaces.
box(12,.15,10,[0,-.09,0],new THREE.MeshStandardMaterial({color:'#759294',roughness:.92}));box(12,3.8,.15,[0,1.85,-4.8],new THREE.MeshStandardMaterial({color:'#b7cdcb',roughness:.85}));box(.15,3.8,10,[-5.9,1.85,0],new THREE.MeshStandardMaterial({color:'#abc4c3',roughness:.85}));
for(let i=-5;i<=5;i++)box(.008,.002,10,[i,.001,0],new THREE.MeshBasicMaterial({color:'#87a0a1'}));for(let i=-4;i<=4;i++)box(12,.002,.008,[0,.001,i],new THREE.MeshBasicMaterial({color:'#87a0a1'}));
const sign=textLabel('IR / SIMULATION SUITE',3.8);sign.position.set(.4,2.9,-4.69);scene.add(sign);box(2.4,1.2,.04,[-3.6,1.9,-4.65],'dark');box(2.25,1.04,.05,[-3.6,1.9,-4.61],new THREE.MeshStandardMaterial({color:'#51676a',roughness:.12,metalness:.4}));
box(1.2,2.65,.08,[4.15,1.3,-4.67],new THREE.MeshStandardMaterial({color:'#7f9c9c'}));box(.32,.65,.03,[4.15,1.96,-4.6],'dark');rod([4.5,1,-4.55],[4.5,1.3,-4.55],.025);
// Hospital fit-out: cabinetry, control-room glass, medical gas, hand hygiene and storage.
const cabinetMat=new THREE.MeshStandardMaterial({color:'#e2e5dc',roughness:.45});
for(let i=0;i<5;i++){const x=-1.5+i*.82;box(.78,.86,.58,[x,.47,-4.25],cabinetMat);box(.8,.055,.64,[x,.93,-4.22],'chrome');for(let j=0;j<3;j++){box(.7,.21,.025,[x,.23+j*.25,-3.945],'white');rod([x-.16,.25+j*.25,-3.91],[x+.16,.25+j*.25,-3.91],.012)}box(.78,.85,.37,[x,2.03,-4.48],cabinetMat);box(.69,.74,.025,[x,2.03,-4.275],'white');rod([x+.22,1.92,-4.23],[x+.22,2.14,-4.23],.012)}
// Sink and hand-hygiene station.
box(.62,.06,.47,[-4.9,1.05,-4.18],'chrome');sphere(.24,.065,.18,[-4.9,1.07,-4.14],'dark');curve([[-4.9,1.1,-4.37],[-4.9,1.38,-4.37],[-4.9,1.38,-4.1],[-4.9,1.25,-4.1]],.025,'chrome');box(.16,.28,.12,[-5.35,1.61,-4.54],'white');box(.12,.12,.13,[-5.35,1.58,-4.51],'blue');const wash=textLabel('HAND HYGIENE',.9);wash.position.set(-4.95,2.3,-4.61);scene.add(wash);
// Glazed control-room partition and operator desk on the left wall.
box(.08,1.5,3.35,[-5.77,2.05,-1.8],'dark');box(.09,1.32,3.12,[-5.70,2.05,-1.8],new THREE.MeshPhysicalMaterial({color:'#8cb6bc',transparent:true,opacity:.38,roughness:.08,metalness:.15}));for(const z of [-3.35,-1.8,-.25])box(.12,1.5,.045,[-5.65,2.05,z],'chrome');box(.85,.08,2.7,[-5.12,1.04,-1.8],'white');for(const z of [-2.5,-1.2]){box(.065,.44,.68,[-5.24,1.43,z],'dark');box(.018,.34,.57,[-5.19,1.43,z],new THREE.MeshBasicMaterial({color:'#8caead'}));box(.32,.025,.6,[-4.99,1.1,z],'dark')}
// Service panel and color-coded outlets.
box(.12,.42,1.45,[-5.72,1.36,1.12],'white');for(let i=0;i<4;i++){const plug=mesh(new THREE.CylinderGeometry(.047,.047,.035,20),i===0?'blue':i===1?'amber':'chrome',[-5.63,1.39,.59+i*.33]);plug.rotation.z=Math.PI/2}const gases=textLabel('MEDICAL GAS / POWER',1.55);gases.rotation.y=Math.PI/2;gases.position.set(-5.60,1.84,1.13);scene.add(gases);
// Supply shelves and packaged sterile kits.
const supplies=new THREE.Group();supplies.position.set(-4.8,0,3.1);scene.add(supplies);for(const x of [-.45,.45])for(const z of [-.25,.25])rod([x,.1,z],[x,2.1,z],.025,'chrome',supplies);for(let j=0;j<4;j++){box(1,.04,.6,[0,.35+j*.51,0],'chrome',supplies);for(let k=0;k<3;k++)box(.24,.25,.35,[-.3+k*.3,.50+j*.51,0],k===1?'teal':'white',supplies)}const stock=textLabel('STERILE SUPPLIES',1.25);stock.position.set(-4.8,2.25,3.1);scene.add(stock);
// Clinical waste, sharps bin, wall rails and ceiling light panels.
box(.45,.65,.45,[3.45,.36,-3.9],'white');box(.47,.08,.47,[3.45,.73,-3.9],'amber');box(.28,.32,.22,[2.45,1.18,-4.05],new THREE.MeshStandardMaterial({color:'#b15448'}));
for(const z of [-3,0,3]){box(.13,.11,1.65,[-5.69,.8,z],'white');const light=box(2,.05,.42,[0,3.72,z],new THREE.MeshStandardMaterial({color:'#fcffff',emissive:'#dbeaf2',emissiveIntensity:.5}));}
box(11.8,.12,.05,[0,.2,-4.68],'dark');box(.05,.12,9.6,[-5.77,.2,0],'dark');
// Table pedestal, longitudinal travel and patient support.
box(.85,.16,1.65,[0,.15,.2],'white');box(.45,.71,.75,[0,.57,.15],'white');box(.66,.11,1.4,[0,.95,.1],'chrome');const table=new THREE.Group();scene.add(table);box(.95,.13,4.9,[0,1.05,0],'dark',table);box(.82,.09,4.6,[0,1.16,0],'teal',table);box(.66,.15,.52,[0,1.24,-1.85],'white',table);rod([-.54,1,-1.3],[-.54,1,1.5],.028,'chrome',table);rod([.54,1,-1.3],[.54,1,1.5],.028,'chrome',table);
box(.63,.09,1.15,[-.73,1.08,-.5],'dark',table);box(.63,.09,1.15,[.73,1.08,-.5],'dark',table);
// Articulated patient mannequin, supine on the table.
const patient=new THREE.Group();table.add(patient);const chest=sphere(.36,.20,.57,[0,1.4,-.69],'skin',patient);sphere(.32,.18,.38,[0,1.4,.05],'skin',patient);sphere(.12,.10,.17,[0,1.39,-1.33],'skin',patient);sphere(.205,.19,.265,[0,1.44,-1.64],'skin',patient);sphere(.043,.028,.065,[0,1.635,-1.59],'skin',patient);
for(const side of [-1,1]){sphere(.045,.063,.07,[side*.20,1.47,-1.64],'skin',patient);sphere(.045,.01,.014,[side*.081,1.609,-1.69],'dark',patient);rod([side*.15,1.36,.30],[side*.18,1.31,1.08],.115,'skin',patient);sphere(.1,.1,.10,[side*.18,1.31,1.08],'joint',patient);rod([side*.18,1.31,1.10],[side*.2,1.28,1.80],.081,'skin',patient);sphere(.095,.085,.20,[side*.2,1.31,1.96],'skin',patient);rod([side*.31,1.42,-1.04],[side*.70,1.26,-.46],.076,'skin',patient);sphere(.071,.068,.068,[side*.70,1.26,-.46],'joint',patient);rod([side*.70,1.26,-.46],[side*.84,1.26,.05],.055,'skin',patient);sphere(.065,.036,.095,[side*.87,1.26,.13],'skin',patient)}
const drapes=new THREE.Group();patient.add(drapes);function drape(z,length,width){const g=new THREE.PlaneGeometry(width,length,18,24);const pos=g.attributes.position;for(let i=0;i<pos.count;i++){let x=pos.getX(i),yy=pos.getY(i);pos.setZ(i,.12*Math.cos(x*2.4)-Math.max(0,Math.abs(x)-.36)*1.2+.014*Math.sin(yy*16+x*11))}g.computeVertexNormals();const m=new THREE.MeshStandardMaterial({color:'#438e89',roughness:1,side:THREE.DoubleSide});const o=mesh(g,m,[0,1.58,z],drapes);o.rotation.x=-Math.PI/2;}drape(-.66,1.16,1.13);drape(1.27,1.35,1.10);
// Access markers remain visible above the mannequin, without claiming a clinical target.
const markers=[];for(const [name,pos] of [['Femoral',[-.21,1.62,.29]],['Brachial',[-.7,1.34,-.46]],['Jugular',[-.12,1.59,-1.28]],['Percutaneous',[-.31,1.61,-.61]],['Dialysis',[-.79,1.34,-.18]]]){const m=mesh(new THREE.TorusGeometry(.052,.012,10,32),new THREE.MeshBasicMaterial({color:'#e6c27d'}),pos,table);m.rotation.x=-Math.PI/2;m.userData.access=name;markers.push(m)}
// Ceiling C-arm, movable around the patient.
const carm=new THREE.Group();carm.position.set(0,1.4,-.4);scene.add(carm);const arc=mesh(new THREE.TorusGeometry(1.20,.13,14,80,Math.PI*1.55),'white',[0,0,0],carm);arc.rotation.z=Math.PI*.23;box(.52,.16,.52,[0,1.19,0],'dark',carm);box(.39,.30,.38,[0,-1.18,0],'white',carm);box(.25,.1,.25,[0,-.98,0],'dark',carm);rod([-1.18,0,0],[-1.65,-.65,0],.10,'white',carm);box(.7,.26,1.25,[-1.68,.21,-.4],'white');rod([-1.68,.32,-.4],[-1.68,.85,-.4],.12,'white');
// CT gantry encircles the translating table in CT mode.
const ct=new THREE.Group();ct.position.set(0,1.5,-1.75);scene.add(ct);mesh(new THREE.TorusGeometry(1.15,.43,24,96),'white',[0,0,0],ct);mesh(new THREE.TorusGeometry(.755,.045,10,96),'dark',[0,0,.35],ct);mesh(new THREE.TorusGeometry(.83,.026,10,96),new THREE.MeshBasicMaterial({color:'#72d4d4'}),[0,0,.42],ct);box(2.85,.38,.95,[0,-1.28,0],'white',ct);const ctSign=textLabel('CT · SIMULATION',1.13,'#547776','#e1eceb');ctSign.position.set(0,1.25,.33);ct.add(ctSign);ct.visible=false;
// Ultrasound cart, trolley, radiation shield and anesthesia apparatus.
const us=new THREE.Group();us.position.set(-2.6,0,1.2);scene.add(us);box(.6,.2,.58,[0,.9,0],'white',us);rod([0,.18,0],[0,1.13,0],.045,'chrome',us);box(.72,.44,.07,[0,1.45,-.1],'dark',us);box(.63,.33,.02,[0,1.45,-.055],new THREE.MeshBasicMaterial({color:'#4b6069'}),us);for(const x of [-.23,.23])for(const z of [-.2,.2])wheel(x,z,us);curve([[.3,1,0],[.65,.85,.2],[.45,.6,.4],[.3,1,.3]],.015,'dark',us);
const trolley=new THREE.Group();trolley.position.set(2.25,0,1.6);scene.add(trolley);box(1.25,.08,.72,[0,1.03,0],'chrome',trolley);box(1.29,.025,.76,[0,1.09,0],'teal',trolley);box(1.15,.06,.66,[0,.4,0],'chrome',trolley);for(const x of [-.52,.52])for(const z of [-.27,.27]){rod([x,.15,z],[x,1.02,z],.025,'chrome',trolley);wheel(x,z,trolley)}const trayDevices=new THREE.Group();trolley.add(trayDevices);
function prepareTray(config){while(trayDevices.children.length){const o=trayDevices.children[0];trayDevices.remove(o);o.traverse(m=>{if(m.geometry)m.geometry.dispose()})}config.kit.forEach((id,i)=>{const x=-.47+(i%6)*.18,z=-.19+Math.floor(i/6)*.23,group=equipmentCatalog[id].group;if(['evoh','nbca','particles','chemo','y90'].includes(id)){mesh(new THREE.CylinderGeometry(.031,.031,.11,12),'transparent',[x,1.16,z],trayDevices);box(.047,.025,.047,[x,1.22,z],id==='evoh'?'dark':id==='nbca'?'amber':'blue',trayDevices)}else if(group==='Catheters'||group==='Drainage'||id==='coils'){const loop=mesh(new THREE.TorusGeometry(.049,.004,6,22),id==='coils'?'chrome':'amber',[x,1.13,z],trayDevices);loop.rotation.x=Math.PI/2;rod([x+.045,1.13,z],[x+.045,1.13,z+.085],.004,'chrome',trayDevices)}else if(id==='ultrasound'){box(.075,.035,.045,[x,1.14,z],'white',trayDevices)}else{rod([x,1.13,z-.075],[x,1.13,z+.055],.006,'chrome',trayDevices);box(.028,.022,.04,[x,1.14,z+.068],group==='Needles'?'blue':'white',trayDevices)}})}

const shield=box(.85,1.6,.028,[-2.15,1.75,-1.7],new THREE.MeshPhysicalMaterial({color:'#9bd4d5',transparent:true,opacity:.24,roughness:.12,metalness:.1}));rod([-2.6,2.6,-1.7],[-1.7,2.6,-1.7],.023);rod([-2.15,2.6,-1.7],[-2.15,3.2,-1.7],.03);box(.9,.65,.03,[-2.15,.6,-1.7],'teal');
box(.65,.9,.66,[2.3,.6,-2.7],'white');box(.8,.13,.7,[2.3,1.11,-2.7],'white');for(const x of [2.05,2.55])wheel(x,-2.8);curve([[2.15,1.2,-2.45],[1.5,1.6,-2.3],[.4,1.6,-2.1],[.1,1.61,-1.77]],.025,'dark');rod([2.7,.1,-1.7],[2.7,2.7,-1.7],.019);rod([2.5,2.6,-1.7],[2.9,2.6,-1.7],.015);box(.17,.33,.075,[2.55,2.35,-1.7],'transparent');curve([[2.55,2.2,-1.7],[2.7,1.5,-1.7],[1.6,1.2,-.5],[.83,1.32,-.25]],.005,'transparent');
// Staff have distinct roles and scrubs. Arms move subtly with the workflow.
const staffGroup=new THREE.Group();scene.add(staffGroup);const animatedStaff=[];
function staff(x,z,angle,material,name){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=angle;staffGroup.add(g);sphere(.22,.30,.15,[0,1.21,0],material,g);sphere(.19,.10,.14,[0,.94,0],material,g);box(.38,.62,.12,[0,1.10,.125],'dark',g);box(.28,.12,.08,[0,1.50,.10],'dark',g);for(const side of [-1,1]){rod([side*.1,.93,0],[side*.12,.25,.03],.064,material,g);sphere(.082,.055,.14,[side*.12,.13,.08],'dark',g);rod([side*.22,1.4,0],[side*.30,1.12,.20],.052,material,g);rod([side*.30,1.12,.2],[side*.18,1.14,.44],.044,material,g);sphere(.05,.043,.075,[side*.18,1.14,.46],'glove',g)}sphere(.13,.17,.13,[0,1.7,0],'skin',g);sphere(.14,.08,.14,[0,1.82,0],material,g);box(.18,.09,.045,[0,1.67,.12],'mask',g);sphere(.022,.016,.01,[-.05,1.73,.13],'dark',g);sphere(.022,.016,.01,[.05,1.73,.13],'dark',g);const tag=textLabel(name,.83,'#e6f2ef','#385d5b');tag.position.set(0,2.03,0);g.add(tag);animatedStaff.push(g);return g}
staff(-1.3,.35,Math.PI/2,'scrub','RESIDENT / ATTENDING');staff(2.4,.35,-Math.PI/2,'nurse','NURSE');staff(1.6,-2.45,-Math.PI/3,'anesthesia','ANESTHESIA');
// Screens use the same live Canvas sources as their enlarged UI displays.
const imagingTexture=new THREE.CanvasTexture(document.getElementById('radiologyCanvas')||document.createElement('canvas'));imagingTexture.colorSpace=THREE.SRGBColorSpace;imagingTexture.generateMipmaps=false;imagingTexture.minFilter=THREE.LinearFilter;
const vitalsCanvas=el('vitalsCanvas'),vctx=vitalsCanvas.getContext('2d'),vitalsTexture=new THREE.CanvasTexture(vitalsCanvas);vitalsTexture.colorSpace=THREE.SRGBColorSpace;vitalsTexture.generateMipmaps=false;vitalsTexture.minFilter=THREE.LinearFilter;
function monitor(pos,size,texture,angle){const g=new THREE.Group();g.position.set(...pos);g.rotation.y=angle;scene.add(g);const screenHeight=texture===imagingTexture?size:size*.5;box(size+.10,screenHeight+.10,.09,[0,0,0],'dark',g);mesh(new THREE.PlaneGeometry(size,screenHeight),new THREE.MeshBasicMaterial({map:texture,toneMapped:false}),[0,0,.051],g);rod([0,-size*.4,0],[0,-pos[1]+.2,0],.035,'chrome',g);box(.65,.1,.45,[0,-pos[1]+.12,0],'dark',g);return g}
monitor([-2.45,2.15,-2.65],1.65,imagingTexture,.25);monitor([2.65,2,-2.2],1.05,vitalsTexture,-.25);
// Device in hand: anatomy anchors, visibly different catheter tips and accessories.
const device=new THREE.Group();table.add(device);const syringe=new THREE.Group();trolley.add(syringe);syringe.position.set(.34,1.2,.15);const barrel=mesh(new THREE.CylinderGeometry(.027,.027,.19,18),'transparent',[0,0,0],syringe);rod([0,-.19,0],[0,-.09,0],.006,'chrome',syringe);const plunger=rod([0,.07,0],[0,.18,0],.009,'white',syringe);box(.06,.008,.04,[0,.18,0],'white',syringe);syringe.rotation.z=Math.PI/2;
const accessPoints={Femoral:[-.21,1.54,.29],Brachial:[-.7,1.29,-.46],Jugular:[-.12,1.51,-1.28],Percutaneous:[-.31,1.54,-.61],Dialysis:[-.79,1.30,-.18]};
function accessKey(){return suite.access.split(' ')[0]}
function clearDevice(){while(device.children.length){const m=device.children[0];device.remove(m);m.traverse(o=>{if(o.geometry)o.geometry.dispose()})}}
function buildDevice(){clearDevice();const toolAliases={uterine:'cobra',renal:'cobra',biliaryDrain:'drain',pleural:'drain',ascites:'drain',tipsNeedle:'needle',coveredStent:'stent',picc:'central',chemo:'particles',oil:'particles',liquidMicro:'microcatheter',evoh:'particles',nbca:'particles'};const t=toolAliases[suite.tool]||suite.tool;let end=[0,.03,0];if(['wire','hydrophilic','microwire'].includes(t)){curve([[0,0,0],[.07,.2,.08],[.02,.45,.18],[-.04,.65,.22],[-.1,.69,.19],[-.12,.65,.16]],t==='microwire'?.003:.005,'chrome',device)}else if(['pigtail','cobra','simmons','vertebral','microcatheter','drain'].includes(t)){let pts=[[0,0,0],[0,.24,.08],[0,.52,.15]];const tips={pigtail:[[.06,.59,.16],[.12,.55,.16],[.10,.49,.16],[.045,.49,.16]],drain:[[.06,.59,.16],[.12,.55,.16],[.10,.49,.16],[.045,.49,.16]],cobra:[[.09,.61,.17],[.16,.59,.17]],simmons:[[.1,.62,.17],[.03,.72,.2],[-.06,.67,.19]],vertebral:[[.1,.65,.18]],microcatheter:[[.04,.65,.18]]};pts.push(...tips[t]);curve(pts,t==='microcatheter'?.007:.012,t==='drain'?'white':'amber',device);box(.04,.10,.04,[0,.11,.025],'blue',device)}else if(['coils','particles','y90'].includes(t)){curve([[0,0,0],[0,.24,.08],[.07,.42,.14]],.008,'amber',device);if(t==='coils'){for(let i=0;i<5;i++){const c=mesh(new THREE.TorusGeometry(.035,.004,6,20),'chrome',[0,.02+i*.012,0],device);c.rotation.x=Math.PI/2}}else box(.08,.16,.08,[.07,.53,.14],t==='y90'?'white':'transparent',device)}else if(t==='ultrasound'){box(.13,.07,.085,[0,.045,0],'white',device);box(.14,.012,.085,[0,.008,0],'dark',device);curve([[0,.05,0],[.06,.18,.05],[.3,.25,.1]],.008,'dark',device)}else if(t==='balloon'){rod([0,0,0],[0,.62,.15],.007,'chrome',device);sphere(.035,.14,.035,[0,.3,.075],'transparent',device);rod([-.02,.19,.05],[.02,.19,.05],.004,'chrome',device);rod([-.02,.43,.105],[.02,.43,.105],.004,'chrome',device)}else if(t==='filter'){for(let i=0;i<8;i++){const a=i*Math.PI/4;rod([0,.32,0],[Math.cos(a)*.09,.1,Math.sin(a)*.09],.003,'chrome',device)}}else if(t==='central'||t==='port'){curve([[0,0,0],[0,.3,.08],[.09,.52,.14]],.012,'white',device);if(t==='port')sphere(.075,.03,.09,[.09,.53,.14],'chrome',device);else{curve([[0,.15,.04],[.1,.21,.07],[.1,.3,.08]],.009,'blue',device)}}else if(t==='stent'){for(let i=0;i<12;i++){const c=mesh(new THREE.TorusGeometry(.043,.003,6,22),'chrome',[0,.10+i*.019,.025+i*.004],device);c.rotation.x=Math.PI/2}}else if(t==='syringe'){mesh(new THREE.CylinderGeometry(.033,.033,.22,20),'transparent',[0,.32,.08],device);rod([0,0,0],[0,.21,.05],.004,'chrome',device);rod([0,.42,.1],[0,.54,.13],.009,'white',device)}else{rod([0,0,0],[0,.48,.14],t==='needle'||t==='micropuncture'?.004:.012,'chrome',device);box(t==='biopsy'?.075:.04,t==='biopsy'?.22:.10,.06,[0,.50,.145],t==='probe'?'dark':'blue',device);if(t==='sheath')curve([[0,.14,.04],[.12,.18,.09],[.17,.28,.14]],.009,'transparent',device)}device.rotation.z=-.5;device.rotation.x=-.2;}
function refreshKit(){const p=lab.getCurrent(),config=suiteConfiguration(p);let filters=['All',...new Set(config.kit.map(k=>equipmentCatalog[k].group))];el('equipmentFilters').innerHTML=filters.map(f=>`<button data-kit-filter="${f}" class="${f===suite.filter?'active':''}">${f}</button>`).join('');el('equipmentTray').innerHTML=config.kit.filter(k=>suite.filter==='All'||equipmentCatalog[k].group===suite.filter).map(k=>{let t=equipmentCatalog[k];return `<button data-tool="${k}" class="${suite.tool===k?'active':''}" aria-pressed="${suite.tool===k}"><span class="tool-symbol">${t.icon}</span><b>${t.name}</b><small>${t.group}</small></button>`}).join('');document.querySelectorAll('[data-kit-filter]').forEach(b=>b.onclick=()=>{suite.filter=b.dataset.kitFilter;refreshKit()});document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{suite.tool=b.dataset.tool;el('autoExchange').checked=false;buildDevice();refreshKit();updateTool();});}
function updateTool(){if(['wire','microwire','microcatheter','particles','syringe'].includes(suite.tool))el('navInstrument').value=suite.tool;const tool=equipmentCatalog[suite.tool];el('activeToolName').textContent=tool.name;el('activeToolDescription').textContent=tool.description;window.RadiologyViewer.configure('tool',suite.tool);window.RadiologyViewer.configure('toolName',tool.name);window.IRNavigation.setTool(suite.tool)}
function chooseAccess(a){suite.access=a;if(['gae','pae'].includes(lab.getCurrent().id)){window.IRNavigation.reset(accessKey(),lab.getCurrent().id,el('pelvicVariant').value);window.IRNavigation.setTool(suite.tool);}document.querySelectorAll('[data-access]').forEach(b=>{b.classList.toggle('active',b.dataset.access===a);b.setAttribute('aria-pressed',b.dataset.access===a)});window.RadiologyViewer.configure('access',accessKey());markers.forEach(m=>{m.visible=suiteConfiguration(lab.getCurrent()).access.some(a=>a.startsWith(m.userData.access));m.material.color.set(m.userData.access===accessKey()?'#f1c875':'#67dde5')});}
function configureProcedure(p){suite.table=0;suite.gantry=0;el('tableTravel').value=0;el('gantryRotation').value=0;window.RadiologyViewer.configure('tableOffset',0);window.RadiologyViewer.configure('projection',0);let config=suiteConfiguration(p);prepareTray(config);accessPoints.Percutaneous=p.id==='thoracentesis'?[-.31,1.54,-1.0]:p.id==='paracentesis'?[.27,1.54,-.1]:p.id==='nephrostomy'?[.31,1.54,-.5]:[-.31,1.54,-.61];markers.find(m=>m.userData.access==='Percutaneous').position.set(...accessPoints.Percutaneous.map((v,i)=>i===1?v+.07:v));suite.filter='All';suite.lastStage=-1;el('autoExchange').checked=!['gae','pae'].includes(p.id);el('autoExchange').disabled=['gae','pae'].includes(p.id);el('suitePlay').hidden=['gae','pae'].includes(p.id);el('suiteProgress').disabled=['gae','pae'].includes(p.id);suite.tool=config.stageTools[0];suite.access=config.access[0];suite.modality=config.modality;el('suiteProcedure').value=p.id;el('suiteCaseTitle').textContent=p.name;el('suiteCaseObjective').textContent=p.objective;el('accessNote').textContent=config.note;el('accessOptions').innerHTML=config.access.map(a=>`<button data-access="${a}" aria-pressed="${a===suite.access}" class="${a===suite.access?'active':''}">${a}</button>`).join('');document.querySelectorAll('[data-access]').forEach(b=>b.onclick=()=>chooseAccess(b.dataset.access));el('suiteChecklist').innerHTML=p.steps.map(s=>`<li>${s[0]}</li>`).join('');el('suiteContrast').disabled=['biopsy','ablation','drain','thoracentesis','paracentesis'].includes(p.type);el('imagingSystem').innerHTML=`<option>${config.modality}</option>`;el('imagingSystem').value=config.modality;setModality(config.modality);chooseAccess(suite.access);buildDevice();refreshKit();updateTool();}
function setModality(mode){suite.modality=mode;ct.visible=mode==='CT';carm.visible=mode==='C-arm';us.visible=true;el('roomMode').textContent=mode.toUpperCase();el('suiteImageLabel').textContent=`${mode==='CT'?'CT':mode==='Ultrasound'?'ULTRASOUND':'FLUOROSCOPY'} / SYNTHETIC`;window.RadiologyViewer.configure('roomModality',mode)}
function contrast(){if(['gae','pae'].includes(lab.getCurrent().id))window.IRNavigation.inject();suite.injectUntil=performance.now()+2000;window.RadiologyViewer.inject();el('suiteContrast').textContent='Contrast running…';setTimeout(()=>{el('suiteContrast').textContent='Inject simulated contrast'},2100)}
// Simulated vital signs with distinct ECG, plethysmographic and capnographic traces.
function drawVitals(t){const hr=Math.round(72+2*Math.sin(t*.19)),sys=Math.round(120+2*Math.sin(t*.07)),dia=Math.round(78+Math.sin(t*.05)),rr=14,et=35;vctx.fillStyle='#040d0b';vctx.fillRect(0,0,640,320);vctx.strokeStyle='#13221d';vctx.lineWidth=1;for(let x=0;x<470;x+=20){vctx.beginPath();vctx.moveTo(x,0);vctx.lineTo(x,320);vctx.stroke()}for(let y=0;y<320;y+=20){vctx.beginPath();vctx.moveTo(0,y);vctx.lineTo(470,y);vctx.stroke()}
 function wave(y,color,fn){vctx.beginPath();for(let x=0;x<458;x++){const val=fn((x/90-t)*1.2);x?vctx.lineTo(x,y-val):vctx.moveTo(x,y-val)}vctx.strokeStyle=color;vctx.lineWidth=2.3;vctx.stroke()}
 const gaussian=(p,center,width,a)=>a*Math.exp(-Math.pow((p-center)/width,2));wave(73,'#84ed91',u=>{let p=((u%1)+1)%1;return gaussian(p,.20,.065,5)-gaussian(p,.39,.02,8)+gaussian(p,.43,.012,42)-gaussian(p,.47,.025,13)+gaussian(p,.7,.10,9)});wave(163,'#71cced',u=>{let p=((u%1)+1)%1;return Math.pow(Math.max(0,Math.sin(p*Math.PI)),3)*25-10+Math.sin(p*11)*3});wave(253,'#edcd74',u=>{let p=(((u*.2)%1)+1)%1;return p<.2?0:p<.3?(p-.2)*230:p<.65?23+(p-.3)*9:p<.72?26*(1-(p-.65)/.07):0});
 vctx.font='14px monospace';vctx.fillStyle='#84ed91';vctx.fillText('ECG II',12,22);vctx.fillStyle='#71cced';vctx.fillText('PLETH',12,112);vctx.fillStyle='#edcd74';vctx.fillText('CO₂',12,209);vctx.fillStyle='#e9f2e9';vctx.fillText('SIMULATED VITALS',466,21);vctx.fillStyle='#8eee95';vctx.font='bold 52px monospace';vctx.fillText(String(hr),492,77);vctx.font='13px monospace';vctx.fillText('HR  /min',553,50);vctx.fillStyle='#79d3ee';vctx.font='bold 42px monospace';vctx.fillText('99',491,140);vctx.font='12px monospace';vctx.fillText('SpO₂ %',550,119);vctx.fillStyle='#f0f2ed';vctx.font='bold 26px monospace';vctx.fillText(`${sys}/${dia}`,479,195);vctx.font='12px monospace';vctx.fillText('NIBP mmHg',483,218);vctx.fillStyle='#ecd37c';vctx.font='bold 26px monospace';vctx.fillText(`${rr}    ${et}`,481,264);vctx.font='11px monospace';vctx.fillText('RR /min   EtCO₂',480,284);vctx.fillStyle='#80958b';vctx.fillText('TEMP 36.7°C',480,306);if(Math.floor(t)%2===0)el('vitalsText').textContent=`HR ${hr} · BP ${sys}/${dia} · SpO₂ 99% · RR ${rr} · EtCO₂ ${et} · Temp 36.7°C`;
}
// Procedure and equipment controls.
el('suiteProcedure').innerHTML=procedures.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');el('suiteProcedure').onchange=e=>lab.select(e.target.value);el('suitePlay').onclick=()=>lab.togglePlay();el('suiteReset').onclick=()=>{lab.reset();el('tableTravel').value=0;el('gantryRotation').value=0;suite.table=0;suite.gantry=0;configureProcedure(lab.getCurrent())};el('suiteProgress').oninput=e=>lab.seek(Number(e.target.value)/1000);el('suiteContrast').onclick=contrast;el('tableTravel').oninput=e=>{suite.table=Number(e.target.value)/100;window.RadiologyViewer.configure('tableOffset',suite.table)};el('gantryRotation').oninput=e=>{suite.gantry=Number(e.target.value)*Math.PI/180;window.RadiologyViewer.configure('projection',suite.gantry)};el('imagingSystem').onchange=e=>setModality(e.target.value);el('showDrape').onchange=e=>drapes.visible=e.target.checked;el('showTeam').onchange=e=>{staffGroup.visible=e.target.checked;document.querySelectorAll('.clinical-person').forEach(x=>x.hidden=!e.target.checked)};el('autoExchange').onchange=()=>{suite.lastStage=-1};el('openProcedureNotes').onclick=()=>lab.show('lab');el('viewImaging').onclick=()=>lab.show('lab');
const presets={room:{p:[7.4,6.5,8.3],t:[0,1.2,0]},overhead:{p:[.05,10,.05],t:[0,1,0]},access:{p:[-2.1,2.55,2.0],t:[-.2,1.45,0]},monitors:{p:[0,3,4.7],t:[-.2,1.9,-2.2]}};let cameraTarget=null;document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{setRoomView(false);document.querySelectorAll('[data-camera]').forEach(x=>x.classList.toggle('active',x===b));let pose=presets[b.dataset.camera];if(b.dataset.camera==='access'){const a=accessPoints[accessKey()]||accessPoints.Femoral;pose={p:[a[0]-2.0,a[1]+1.2,a[2]+2.0],t:[a[0],a[1],a[2]+suite.table]}}cameraTarget={p:new THREE.Vector3(...pose.p),t:new THREE.Vector3(...pose.t)}});controls.addEventListener('start',()=>cameraTarget=null);
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();let pointerDown=null;renderer.domElement.addEventListener('pointerdown',e=>pointerDown=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!pointerDown||Math.hypot(e.clientX-pointerDown[0],e.clientY-pointerDown[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObjects(markers).find(h=>h.object.visible);if(hit){const option=suiteConfiguration(lab.getCurrent()).access.find(a=>a.startsWith(hit.object.userData.access));if(option)chooseAccess(option)}});
function resize(){const w=host.clientWidth,h=host.clientHeight;if(w&&h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}}
new ResizeObserver(resize).observe(host);window.addEventListener('ir:procedure',e=>configureProcedure(e.detail));window.addEventListener('ir:section',resize);configureProcedure(lab.getCurrent());resize();suite.ready=true;
el('pinMonitors').onclick=()=>{const pinned=el('pinMonitors').getAttribute('aria-pressed')!=='true';el('pinMonitors').setAttribute('aria-pressed',String(pinned));el('pinMonitors').textContent=pinned?'Unpin side monitors':'Pin monitors to side';document.querySelector('.monitor-column').hidden=!pinned;document.querySelector('.suite-workstation').classList.toggle('unpinned',!pinned);resize()};

const photoImaging=el('clinicalImaging').getContext('2d'),photoVitals=el('clinicalVitals').getContext('2d');
function setRoomView(clinical){el('clinicalRoom').hidden=!clinical;host.hidden=clinical;el('clinicalView').classList.toggle('active',clinical);if(!clinical)enable3D();resize()}el('clinicalView').onclick=()=>setRoomView(true);
window.addEventListener('ir:role',e=>{if(!host.hidden)el('showTeam').checked=true});
window.addEventListener('ir:shield',e=>{animatedStaff.forEach((g,i)=>{if(!g.userData.home)g.userData.home=g.position.clone();g.position.copy(e.detail?new THREE.Vector3(-4.95+i*.6,0,-3.3):g.userData.home)})});
const blood=mesh(new THREE.SphereGeometry(.023,12,8),new THREE.MeshStandardMaterial({color:'#71262e',roughness:.6}),[-.21,1.635,.29],table);blood.scale.y=.07;blood.visible=false;window.addEventListener('ir:blood',e=>blood.visible=e.detail);
const mini=el('suiteImaging').getContext('2d');let previous=0;
function syncEquipment(p){const stage=Math.min(4,Math.floor(p*5));if(stage!==suite.lastStage){suite.lastStage=stage;if(el('autoExchange').checked){const cfg=suiteConfiguration(lab.getCurrent()),preferred=cfg.stageTools[stage];if(cfg.kit.includes(preferred)){suite.tool=preferred;buildDevice();refreshKit();updateTool()}}}}
function animate(ms){requestAnimationFrame(animate);if(document.hidden||ms-previous<1000/24)return;previous=ms;syncEquipment(lab.getProgress());if(el('suite').hidden)return;const t=ms/1000,p=lab.getProgress(),playing=lab.isPlaying();table.position.z=suite.table;carm.rotation.z=suite.gantry;ct.rotation.z=suite.modality==='CT'?Math.sin(t*.2)*.006:0;const ambient=!document.body.classList.contains('no-motion');chest.scale.y=.20+(ambient?Math.sin(t*1.4)*.004:0);drapes.position.y=ambient?Math.sin(t*1.4)*.002:0;animatedStaff.forEach((g,i)=>g.rotation.z=ambient?Math.sin(t*.55+i)*.005:0);const a=accessPoints[accessKey()]||accessPoints.Femoral;device.position.set(a[0],a[1]+.22*(1-Math.min(1,p*2.5)),a[2]);device.scale.setScalar(suite.tool==='ultrasound'?1:1-.12*Math.min(1,p*2));device.visible=p>0||!!suite.tool;plunger.position.y=ms<suite.injectUntil?-.04*Math.sin((suite.injectUntil-ms)/2000*Math.PI):0;markers.forEach(m=>m.scale.setScalar(1+Math.sin(t*3)*.12));
 drawVitals(t);vitalsTexture.needsUpdate=true;const imaging=document.getElementById('radiologyCanvas');if(imaging){if(imagingTexture.image!==imaging)imagingTexture.image=imaging;imagingTexture.needsUpdate=true;mini.drawImage(imaging,0,0,640,640);photoImaging.drawImage(imaging,0,0,640,640);photoVitals.drawImage(vitalsCanvas,0,0,640,320)}
 el('suiteProgress').value=Math.round(p*1000);el('suitePlay').textContent=playing?'Ⅱ Pause guided run':p>=1?'↺ Replay guided run':'▶ Start guided run';const stage=Math.min(4,Math.floor(p*5));el('suiteStage').textContent=`0${stage+1} / ${lab.getCurrent().steps[stage][0].toUpperCase()}`;Array.from(el('suiteChecklist').children).forEach((li,i)=>{li.classList.toggle('active',i===stage);li.classList.toggle('done',i<stage)});
 if(cameraTarget){camera.position.lerp(cameraTarget.p,.085);controls.target.lerp(cameraTarget.t,.085);if(camera.position.distanceTo(cameraTarget.p)<.025)cameraTarget=null}controls.update();if(!host.hidden)renderer.render(scene,camera)}requestAnimationFrame(animate);

window.addEventListener('pagehide',()=>{if(!renderer.isFallback){renderer.dispose();renderer.forceContextLoss()}});

window.addEventListener('ir:procedure',()=>{blood.visible=false});

window.addEventListener('ir:select-tool',e=>{if(!suiteConfiguration(lab.getCurrent()).kit.includes(e.detail))return;suite.tool=e.detail;el('autoExchange').checked=false;buildDevice();refreshKit();updateTool()});
